CREATE TABLE REPINVENTARIO (
    COD INTEGER NOT NULL PRIMARY KEY,
    CODEMPRESA VARCHAR2(4) NOT NULL,
    NUMEROINV NUMBER NOT NULL
);

CREATE TABLE REPINVENTARIODETALLE (
    COD INTEGER NOT NULL PRIMARY KEY,
    BARCODE INTEGER NOT NULL,
    QUANTITY INTEGER NOT NULL,
    CODINVENTARIO INTEGER NOT NULL
);

ALTER TABLE REPINVENTARIO
ADD CONSTRAINT FK_REPINVENTARIO FOREIGN KEY (CODEMPRESA) REFERENCES GAS_EMPRESA (CODIGO_EMPRESA);

ALTER TABLE REPINVENTARIODETALLE
ADD CONSTRAINT FK_REPINVENTARIODETALLE FOREIGN KEY (CODINVENTARIO) REFERENCES REPINVENTARIO (COD);